@startuml
'https://plantuml.com/sequence-diagram
actor HR as "Department Manager"

rectangle Database

rectangle "World" {
    usecase UC3 as "Get contintent list"

    usecase UC4 as "Get country list"

    usecase UC5 as "Get city list"

    usecase UC6 as "Capital?"


    HR - UC3
    UC3 ..> UC4
    UC4 ..> UC5
    UC5 ..> UC6
    UC6 -> UC5
    UC3 - Database
}

@enduml