@startuml
'https://plantuml.com/sequence-diagram
actor HR as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get employee´s details "

    usecase UCa as "Supported Promotion Request"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml