@startuml
'https://plantuml.com/sequence-diagram
actor HR as "Department Manager"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get salary in "

    usecase UCa as "Print salaries"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml