@startuml
'https://plantuml.com/sequence-diagram
actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Delete an employee's information"

    usecase UCa as "data retention legislation"

    HR - UC4
    UC4 ..> UCa : Compliant with
    UC4 - Database
}

@enduml